USE `coms363_proj3`;
SET SQL_SAFE_UPDATES=0;

-- user is the table name, you can replace to your corresponding defined table name
update user set ofstate = 'Florida' where ofstate = 'FL';
update user set ofstate = 'Alabama' where ofstate = 'AL';
update user set ofstate = 'Alaska' where ofstate = 'AK';
update user set ofstate = 'Arizona' where ofstate = 'AZ';
update user set ofstate = 'Arkansas' where ofstate = 'AR';
update user set ofstate = 'California' where ofstate = 'CA';
update user set ofstate = 'Connecticut' where ofstate = 'CT';
update user set ofstate = 'Delaware' where ofstate = 'DE';
update user set ofstate = 'District of Columbia' where ofstate = 'DC';
update user set ofstate = 'Florida' where ofstate = 'FL';
update user set ofstate = 'Georgia' where ofstate = 'GA';
update user set ofstate = 'Hawaii' where ofstate = 'HI';
update user set ofstate = 'Idaho' where ofstate = 'ID';
update user set ofstate = 'Illinois' where ofstate = 'IL';
update user set ofstate = 'Indiana' where ofstate = 'IN';
update user set ofstate = 'Iowa' where ofstate = 'IA';
update user set ofstate = 'Kansas' where ofstate = 'KS';
update user set ofstate = 'Kentucky' where ofstate = 'KY';
update user set ofstate = 'Louisiana' where ofstate = 'LA';
update user set ofstate = 'Maine' where ofstate = 'ME';
update user set ofstate = 'Maryland' where ofstate = 'MD';
update user set ofstate = 'Massachusetts' where ofstate = 'MA';
update user set ofstate = 'Michigan' where ofstate = 'MI';
update user set ofstate = 'Minnesota' where ofstate = 'MN';
update user set ofstate = 'Mississippi' where ofstate = 'MS';
update user set ofstate = 'Missouri' where ofstate = 'MO';
update user set ofstate = 'Montana' where ofstate = 'MT';
update user set ofstate = 'Nebraska' where ofstate = 'NE';
update user set ofstate = 'Nevada' where ofstate = 'NV';
update user set ofstate = 'New Hampshire' where ofstate = 'NH';
update user set ofstate = 'New Jersey' where ofstate = 'NJ';
update user set ofstate = 'New Mexico' where ofstate = 'NM';
update user set ofstate = 'New York' where ofstate = 'NY';
update user set ofstate = 'North Carolina' where ofstate = 'NC';
update user set ofstate = 'North Dakota' where ofstate = 'ND';
update user set ofstate = 'Ohio' where ofstate = 'OH';
update user set ofstate = 'Oklahoma' where ofstate = 'OK';
update user set ofstate = 'Oregon' where ofstate = 'OR';
update user set ofstate = 'Pennsylvania' where ofstate = 'PA';
update user set ofstate = 'Rhode Island' where ofstate = 'RI';
update user set ofstate = 'South Carolina' where ofstate = 'SC';
update user set ofstate = 'South Dakota' where ofstate = 'SD';
update user set ofstate = 'Tennessee' where ofstate = 'TN';
update user set ofstate = 'Texas' where ofstate = 'TX';
update user set ofstate = 'Utah' where ofstate = 'UT';
update user set ofstate = 'Vermont' where ofstate = 'VT';
update user set ofstate = 'Virginia' where ofstate = 'VA';
update user set ofstate = 'Washington' where ofstate = 'WA';
update user set ofstate = 'West Virginia' where ofstate = 'WV';
update user set ofstate = 'Wisconsin' where ofstate = 'WI';
update user set ofstate = 'Wyoming' where ofstate = 'WY';


-- select * from user where ofstate = 'FL';